FROM node:18-alpine

WORKDIR /usr/src/app

# Instala dependências necessárias
RUN apk add --no-cache \
    curl \
    postgresql-client

# Copia os arquivos de configuração
COPY package*.json ./
COPY tsconfig.json ./

# Instala as dependências
RUN npm install

# Copia o código fonte
COPY . .

# Expõe a porta
EXPOSE 3000

# Comando para iniciar em modo de desenvolvimento
CMD ["npm", "run", "dev"] 